/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_rescrv_ygor_DataLogger */

#ifndef _Included_net_rescrv_ygor_DataLogger
#define _Included_net_rescrv_ygor_DataLogger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    record
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_net_rescrv_ygor_DataLogger_record
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    time
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_rescrv_ygor_DataLogger_time
  (JNIEnv *, jclass);

/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_rescrv_ygor_DataLogger_initialize
  (JNIEnv *, jclass);

/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_rescrv_ygor_DataLogger_terminate
  (JNIEnv *, jclass);

/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    _create
 * Signature: (Ljava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_net_rescrv_ygor_DataLogger__1create
  (JNIEnv *, jobject, jstring, jlong, jlong);

/*
 * Class:     net_rescrv_ygor_DataLogger
 * Method:    _destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_rescrv_ygor_DataLogger__1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
